services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-next
    ports:
      - '3030:3030'
    restart: unless-stopped
    env_file:
      - .env.local
    command: yarn dev